# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [1]:
import numpy as np

2. Create a null vector of size 10 

In [2]:
x = np.zeros(10)

3. Create a vector with values ranging from 10 to 49

In [3]:
vec1 = np.arange(10, 50)


4. Find the shape of previous array in question 3

In [4]:
vec1.shape

(40,)

5. Print the type of the previous array in question 3

In [5]:
vec1.dtype

dtype('int32')

6. Print the numpy version and the configuration


In [6]:
print(np.__version__)
print(np.show_config())

1.18.5
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/ikram/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/ikram/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/ikram/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\

7. Print the dimension of the array in question 3


In [7]:
vec1.ndim

1

8. Create a boolean array with all the True values

In [8]:
booArray = np.array([1,2,3,4,5,6], dtype=bool);
booArray

array([ True,  True,  True,  True,  True,  True])

9. Create a two dimensional array




In [9]:
arr2D = np.arange(20).reshape(4,5);
arr2D

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

10. Create a three dimensional array



In [10]:
arr3D = np.arange(45).reshape(3, 3, 5);
arr3D

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44]]])

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [11]:
np.flip(arr2D)

array([[19, 18, 17, 16, 15],
       [14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5],
       [ 4,  3,  2,  1,  0]])

12. Create a null vector of size 10 but the fifth value which is 1 

In [12]:
x = np.zeros(10, dtype=int);
x[4] = 1;
x

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

13. Create a 3x3 identity matrix

In [13]:
im3x3 = np.identity(3);
im3x3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [14]:
arr = np.array([1, 2, 3, 4, 5], dtype=float);
arr

array([1., 2., 3., 4., 5.])

15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [15]:
arr1 = np.array([[1., 2., 3.],[4., 5., 6.]]);
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]]);
arr3 = arr1*arr2;
arr3

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [16]:
arr1 = np.array([[1., 2., 3.],[4., 5., 6.]]) ;
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]]);

compArr = arr1 == arr2;
compArr

array([[False, False, False],
       [False, False, False]])

17. Extract all odd numbers from arr with values(0-9)

In [17]:
a = np.arange(0, 10);

b = a[a % 2 == 1];

b

array([1, 3, 5, 7, 9])

18. Replace all odd numbers to -1 from previous array

In [18]:
a[a%2 == 1] = -1
a

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [19]:
arr = np.arange(10)
arr[5:9] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

20. Create a 2d array with 1 on the border and 0 inside

In [20]:
x = np.ones((4,4))
x[1:3, 1:3] = 0
x

array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [21]:
arr2d = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]]);
arr2d[1,1] = 12;
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [22]:
arr3d = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])

arr3d[0][0] = 64

arr3d

array([[[64, 64, 64],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [23]:
arr1 = np.arange(9).reshape(3,3)
arr2 = arr1[0]
arr2

array([0, 1, 2])

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [24]:
arr1 = np.arange(9).reshape(3,3)
val = arr1[1][1]
val

4

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [25]:
arr1 = np.arange(9).reshape(3,3)
arr3 = arr1[:-1, -1]
arr3

array([2, 5])

26. Create a 10x10 array with random values and find the minimum and maximum values

In [26]:
arr = np.arange(100).reshape(10,10)
maxInRows = np.amax(arr, axis=0)
val = max(maxInRows)
val

99

27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [27]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 

b = np.array([7,2,10,2,7,4,9,4,9,8])

np.intersect1d(a, b)

array([2, 4])

28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [28]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.where(a == b)

(array([1, 3, 5, 7], dtype=int64),)

29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [47]:
import random

name = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  
data = np.random.randn(7, 4)
data[names != "Will"]

array([[-1.82853919,  0.13710696, -1.80675104,  0.47373231],
       [-0.15595794,  0.97878463, -0.16121314, -1.33609554],
       [ 0.55659859, -1.04937118, -0.10588574,  0.0413288 ],
       [-1.68357831, -0.36716268, -1.70395232, -0.05189605],
       [-0.39564402, -1.78569381,  1.06365363,  1.37313531]])

30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [46]:
name = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  
data = np.random.randn(7, 4)

data [(names != 'Will') & (names != 'Joe')]


array([[ 0.86877321,  0.51217866, -0.70796525, -0.21085261],
       [-0.88706452, -1.90097174, -0.450419  ,  0.46342835]])

Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [31]:
arr2d = np.random.uniform(low=1.0, high=15.0, size=(5,3))
arr2d

array([[ 1.24876479,  6.23618748,  9.04586804],
       [ 2.43998019,  1.05940371, 13.63408073],
       [ 5.47510841,  7.45630318,  3.41326392],
       [12.25060293,  4.63107917,  1.47300638],
       [13.47929062,  4.16642533,  3.67620036]])

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [32]:
arr3d = np.random.uniform(low=1.0, high=16.0, size=(2, 2, 4))
arr3d

array([[[ 5.81061473,  5.06179381, 14.22787671, 15.82003367],
        [ 9.49914836,  7.53952131,  6.47429031,  8.89372606]],

       [[ 2.39632728,  9.6905119 ,  9.13535683,  1.929968  ],
        [ 3.86045675,  3.8943463 ,  6.67040563,  4.1757113 ]]])

33. Swap axes of the array you created in Question 32

In [33]:
arr3d = np.swapaxes(arr3d, 0, 1)
arr3d

array([[[ 5.81061473,  5.06179381, 14.22787671, 15.82003367],
        [ 2.39632728,  9.6905119 ,  9.13535683,  1.929968  ]],

       [[ 9.49914836,  7.53952131,  6.47429031,  8.89372606],
        [ 3.86045675,  3.8943463 ,  6.67040563,  4.1757113 ]]])

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [34]:
import math

arr = np.random.random(10)
print(arr)
new_arr = np.sqrt(arr)
new_arr = np.where(new_arr < 0.5, 0, new_arr)
new_arr

[0.09195768 0.83360525 0.75469966 0.78781667 0.2955708  0.51988567
 0.45018579 0.10491119 0.06000174 0.77954144]


array([0.        , 0.91301985, 0.86873451, 0.88759037, 0.54366424,
       0.72103098, 0.67095886, 0.        , 0.        , 0.88291644])

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [50]:
arr1 = np.random.random(12)
arr2 = np.random.random(12)
print(arr1)
print(arr2)
maxVal = (np.amax(arr1), np.amax(arr2))
arrMax = np.array([maxVal])
arrMax

[0.57329488 0.21241158 0.47988616 0.87133551 0.55355045 0.70463457
 0.29261064 0.62455879 0.93192642 0.4265065  0.13618885 0.45637642]
[0.00579995 0.07388928 0.65292935 0.27244025 0.56036024 0.39858327
 0.7976644  0.99774409 0.18156185 0.11809107 0.9955268  0.05614692]


array([[0.93192642, 0.99774409]])

36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [37]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
a = np.unique(names)
np.sort(a)
a

array(['Bob', 'Joe', 'Will'], dtype='<U4')

37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [53]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
val = np.intersect1d(a, b)

a = filter(lambda x: x if x not in val else None, a)
np.asarray(list(a))

array([1, 2, 3, 4])

38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [39]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
newColumn = np.array([[10,10,10]])

sampleArray[:, 1] = newColumn
sampleArray


array([[34, 10, 73],
       [82, 10, 12],
       [53, 10, 66]])

39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [40]:
x = np.array([[1., 2., 3.], [4., 5., 6.]]) 
y = np.array([[6., 23.], [-1, 7], [8, 9]])

np.dot(x, y)

array([[ 28.,  64.],
       [ 67., 181.]])

40. Generate a matrix of 20 random values and find its cumulative sum

In [54]:
mat1 = np.random.rand(4,5)
print(mat1)
np.cumsum(mat1)

[[0.51365903 0.67787173 0.27482183 0.60401465 0.85687812]
 [0.00756576 0.42645107 0.1586431  0.08850712 0.6718077 ]
 [0.53518052 0.23252856 0.4934698  0.47470726 0.34531279]
 [0.94671485 0.00452985 0.55248422 0.93820749 0.6669494 ]]


array([0.51365903, 1.19153076, 1.46635258, 2.07036723, 2.92724535,
       2.93481111, 3.36126219, 3.51990529, 3.60841241, 4.2802201 ,
       4.81540063, 5.04792919, 5.54139898, 6.01610624, 6.36141903,
       7.30813388, 7.31266373, 7.86514795, 8.80335543, 9.47030483])