# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [16]:
import numpy as np

2. Create a null vector of size 10 

In [17]:
x = np.zeros(10)
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3. Create a vector with values ranging from 10 to 49

In [18]:
vec1 = np.arange(10, 50)
vec1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

4. Find the shape of previous array in question 3

In [19]:
vec1.shape

(40,)

5. Print the type of the previous array in question 3

In [20]:
vec1.dtype

dtype('int32')

6. Print the numpy version and the configuration


In [21]:
print(np.__version__)
print(np.show_config())

1.18.5
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/ikram/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/ikram/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/ikram/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\

7. Print the dimension of the array in question 3


In [22]:
vec1.ndim

1

8. Create a boolean array with all the True values

In [23]:
booArray = np.array([1,2,3,4,5,6], dtype=bool);
booArray

array([ True,  True,  True,  True,  True,  True])

9. Create a two dimensional array




In [24]:
arr2D = np.arange(20).reshape(4,5);
arr2D

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

10. Create a three dimensional array



In [25]:
arr3D = np.arange(45).reshape(3, 3, 5);
arr3D

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44]]])

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [26]:
np.flip(arr2D)

array([[19, 18, 17, 16, 15],
       [14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5],
       [ 4,  3,  2,  1,  0]])

12. Create a null vector of size 10 but the fifth value which is 1 

In [27]:
x = np.zeros(10, dtype=int);
x[4] = 1;
x

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

13. Create a 3x3 identity matrix

In [28]:
im3x3 = np.identity(3);
im3x3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [57]:
arr = np.array([1, 2, 3, 4, 5])
arr.astype(float)

array([1., 2., 3., 4., 5.])

15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [30]:
arr1 = np.array([[1., 2., 3.],[4., 5., 6.]]);
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]]);
arr3 = arr1*arr2;
arr3

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [31]:
arr1 = np.array([[1., 2., 3.],[4., 5., 6.]]) ;
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]]);

compArr = arr1 == arr2;
compArr

array([[False, False, False],
       [False, False, False]])

17. Extract all odd numbers from arr with values(0-9)

In [32]:
a = np.arange(0, 10);

b = a[a % 2 == 1];

b

array([1, 3, 5, 7, 9])

18. Replace all odd numbers to -1 from previous array

In [33]:
a[a%2 == 1] = -1
a

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [34]:
arr = np.arange(10)
arr[5:9] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

20. Create a 2d array with 1 on the border and 0 inside

In [35]:
x = np.ones((4,4))
x[1:3, 1:3] = 0
x

array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [36]:
arr2d = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]]);
arr2d[1,1] = 12;
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [37]:
arr3d = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])

arr3d[0][0] = 64

arr3d

array([[[64, 64, 64],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [38]:
arr1 = np.arange(9).reshape(3,3)
arr2 = arr1[0]
arr2

array([0, 1, 2])

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [39]:
arr1 = np.arange(9).reshape(3,3)
val = arr1[1][1]
val

4

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [40]:
arr1 = np.arange(9).reshape(3,3)
arr3 = arr1[:-1, -1]
arr3

array([2, 5])

26. Create a 10x10 array with random values and find the minimum and maximum values

In [41]:
arr = np.arange(100).reshape(10,10)
maxInRows = np.amax(arr, axis=0)
val = max(maxInRows)
val

99

27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [42]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 

b = np.array([7,2,10,2,7,4,9,4,9,8])

np.intersect1d(a, b)

array([2, 4])

28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [43]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.where(a == b)

(array([1, 3, 5, 7], dtype=int64),)

29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [44]:
import random

names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  
data = np.random.randn(7, 4)
data[names != "Will"]

array([[ 1.33388893, -0.10587474, -1.65680444,  0.23371967],
       [ 2.08979875, -0.73427687,  0.93706507,  0.19025842],
       [ 0.32090172,  0.43396967,  0.56802821,  0.59437295],
       [ 0.58847585,  0.15717759,  0.53343315, -0.91034934],
       [-1.58623379, -0.88457951,  0.04908436,  1.17144449]])

30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [45]:
name = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  
data = np.random.randn(7, 4)

data [(names != 'Will') & (names != 'Joe')]

array([[-0.25992999,  0.37734708,  1.13024782, -0.10896016],
       [-0.39216016, -0.96054489, -0.98287776, -0.34557081]])

Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [46]:
arr2d = np.random.uniform(low=1.0, high=15.0, size=(5,3))
arr2d

array([[ 3.62161253,  9.68815355,  6.71122848],
       [ 1.8789089 , 11.96645154,  6.87724902],
       [11.07036196,  6.15863569,  1.01754586],
       [13.24914729, 10.23244212, 10.45272472],
       [13.20085041,  2.29816108,  4.11525393]])

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [47]:
arr3d = np.random.uniform(low=1.0, high=16.0, size=(2, 2, 4))
arr3d

array([[[14.21183048,  1.21113697,  7.34526043, 10.82691541],
        [13.0306473 ,  6.22265137,  5.34376135,  5.66994498]],

       [[ 8.96638716,  1.83154258, 15.20502702, 15.57709251],
        [14.77507715,  9.98348263,  6.32860163, 14.66343674]]])

33. Swap axes of the array you created in Question 32

In [48]:
arr3d = np.swapaxes(arr3d, 0, 1)
arr3d

array([[[14.21183048,  1.21113697,  7.34526043, 10.82691541],
        [ 8.96638716,  1.83154258, 15.20502702, 15.57709251]],

       [[13.0306473 ,  6.22265137,  5.34376135,  5.66994498],
        [14.77507715,  9.98348263,  6.32860163, 14.66343674]]])

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [58]:
import math

arr = np.random.random(10)
print(arr)

new_arr = np.sqrt(arr)
new_arr = np.where(new_arr < 0.5, 0, new_arr)
new_arr

[0.81235258 0.78291572 0.19250852 0.94862914 0.18666191 0.24462349
 0.37424388 0.32210199 0.9539903  0.55691805]


array([0.90130604, 0.88482525, 0.        , 0.97397595, 0.        ,
       0.        , 0.61175475, 0.5675403 , 0.97672427, 0.74626942])

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [50]:
arr1 = np.random.random(12)
arr2 = np.random.random(12)

maxVal = (np.amax(arr1), np.amax(arr2))
arrMax = np.array([maxVal])

print("arrMax= ", arrMax)

arrMax=  [[0.91497713 0.97535014]]


36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [51]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
a = np.unique(names)
np.sort(a)
a

array(['Bob', 'Joe', 'Will'], dtype='<U4')

37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [52]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
val = np.intersect1d(a, b)
a = np.delete(a, np.where(a == val))
a

array([1, 2, 3, 4])

38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [53]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
newColumn = np.array([[10,10,10]])

sampleArray[:, 1] = newColumn
sampleArray


array([[34, 10, 73],
       [82, 10, 12],
       [53, 10, 66]])

39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [54]:
x = np.array([[1., 2., 3.], [4., 5., 6.]]) 
y = np.array([[6., 23.], [-1, 7], [8, 9]])

np.dot(x, y)

array([[ 28.,  64.],
       [ 67., 181.]])

40. Generate a matrix of 20 random values and find its cumulative sum

In [55]:
mat1 = np.random.rand(4,5)
np.cumsum(mat1)

array([0.19484015, 0.7880474 , 1.66678548, 1.8616686 , 2.20799192,
       2.23679338, 2.37463443, 2.70602978, 3.30667478, 3.96885779,
       4.84620652, 5.83295415, 6.67465889, 6.93376055, 7.55142733,
       7.95682045, 8.17776849, 8.17928623, 8.79731685, 9.22234988])