# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [1]:
import numpy as np

2. Create a null vector of size 10 

In [2]:
x = np.zeros(10)

3. Create a vector with values ranging from 10 to 49

In [3]:
vec1 = np.arange(10, 50)


4. Find the shape of previous array in question 3

In [55]:
vec1.shape

(40,)

5. Print the type of the previous array in question 3

In [54]:
vec1.dtype

dtype('int32')

6. Print the numpy version and the configuration


In [254]:
print(np.__version__)
print(np.show_config())

1.18.5
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/ikram/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/ikram/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/ikram/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\

7. Print the dimension of the array in question 3


In [52]:
vec1.ndim

1

8. Create a boolean array with all the True values

In [51]:
booArray = np.array([1,2,3,4,5,6], dtype=bool);
booArray

array([ True,  True,  True,  True,  True,  True])

9. Create a two dimensional array




In [255]:
arr2D = np.arange(20).reshape(4,5);
arr2D

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

10. Create a three dimensional array



In [56]:
arr3D = np.arange(45).reshape(3, 3, 5);
arr3D

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44]]])

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [11]:
np.flip(arr2D)

array([[19, 18, 17, 16, 15],
       [14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5],
       [ 4,  3,  2,  1,  0]])

12. Create a null vector of size 10 but the fifth value which is 1 

In [57]:
x = np.zeros(10, dtype=int);
x[4] = 1;
x

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

13. Create a 3x3 identity matrix

In [58]:
im3x3 = np.identity(3);
im3x3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [59]:
arr = np.array([1, 2, 3, 4, 5], dtype=float);
arr

array([1., 2., 3., 4., 5.])

15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [60]:
arr1 = np.array([[1., 2., 3.],[4., 5., 6.]]);
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]]);
arr3 = arr1*arr2;
arr3

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [61]:
arr1 = np.array([[1., 2., 3.],[4., 5., 6.]]) ;
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]]);

compArr = arr1 == arr2;
compArr

array([[False, False, False],
       [False, False, False]])

17. Extract all odd numbers from arr with values(0-9)

In [64]:
a = np.arange(0, 10);

b = a[a % 2 == 1];

b

array([1, 3, 5, 7, 9])

18. Replace all odd numbers to -1 from previous array

In [63]:
a[a%2 == 1] = -1
a

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [65]:
arr = np.arange(10)
arr[5:9] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

20. Create a 2d array with 1 on the border and 0 inside

In [66]:
x = np.ones((4,4))
x[1:3, 1:3] = 0
x

array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [67]:
arr2d = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]]);
arr2d[1,1] = 12;
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [82]:
arr3d = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])

arr3d[0][0] = 64

arr3d

array([[[64, 64, 64],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [87]:
arr1 = np.arange(9).reshape(3,3)
arr2 = arr1[0]
arr2

array([0, 1, 2])

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [94]:
arr1 = np.arange(9).reshape(3,3)
val = arr1[1][1]
val

4

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [95]:
arr1 = np.arange(9).reshape(3,3)
arr3 = arr1[:-1, -1]
arr3

array([2, 5])

26. Create a 10x10 array with random values and find the minimum and maximum values

In [96]:
arr = np.arange(100).reshape(10,10)
maxInRows = np.amax(arr, axis=0)
val = max(maxInRows)
val

99

27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [97]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 

b = np.array([7,2,10,2,7,4,9,4,9,8])

np.intersect1d(a, b)

array([2, 4])

28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [98]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.where(a == b)

(array([1, 3, 5, 7], dtype=int64),)

29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [148]:
import random

name = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  
data = np.random.randn(7, 4)

dataInt = data.astype(int)

print(dataInt)
print(np.where(name[dataInt] != "Will"))

[[ 0  0 -1  0]
 [ 1  0  0  1]
 [ 0  0  0  0]
 [ 0  0  0  0]
 [ 0  1 -1  0]
 [ 0  0  2  0]
 [ 0  0  0  0]]
(array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5,
       5, 6, 6, 6, 6], dtype=int64), array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1,
       3, 0, 1, 2, 3], dtype=int64))


30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [147]:
name = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  
data = np.random.randn(7, 4)

dataInt = data.astype(int)

print(dataInt)
print(np.where((name[dataInt] != "Will") & (name[dataInt] != "Joe")))

[[ 0  1  0  0]
 [ 0  1  0  0]
 [ 1 -1  0  1]
 [ 0  0  1 -1]
 [-1  0  0  0]
 [-1  0  0 -1]
 [ 0  0 -2  0]]
(array([0, 0, 0, 1, 1, 1, 2, 3, 3, 4, 4, 4, 5, 5, 6, 6, 6], dtype=int64), array([0, 2, 3, 0, 2, 3, 2, 0, 1, 1, 2, 3, 1, 2, 0, 1, 3], dtype=int64))


Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [150]:
arr2d = np.random.uniform(low=1.0, high=15.0, size=(5,3))
arr2d

array([[ 1.69705725,  3.36883977, 14.51115455],
       [ 7.94949702,  7.791638  ,  8.20908023],
       [10.00085824, 14.11766206, 13.35504786],
       [ 1.16358114,  2.83106704, 10.73464692],
       [ 5.4108342 ,  2.03889683,  2.33360266]])

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [151]:
arr3d = np.random.uniform(low=1.0, high=16.0, size=(2, 2, 4))
arr3d

array([[[15.14797062,  5.48868198,  7.68427838,  4.67360728],
        [ 7.27745545, 14.68993987,  4.68116199, 13.99939474]],

       [[ 8.20278991, 15.61492736, 11.19914221,  5.7634569 ],
        [ 4.03976519,  6.79810095,  6.33646032, 10.55251032]]])

33. Swap axes of the array you created in Question 32

In [157]:
arr3d = np.swapaxes(arr3d, 0, 1)
arr3d

array([[[15.14797062,  7.27745545],
        [ 5.48868198, 14.68993987],
        [ 7.68427838,  4.68116199],
        [ 4.67360728, 13.99939474]],

       [[ 8.20278991,  4.03976519],
        [15.61492736,  6.79810095],
        [11.19914221,  6.33646032],
        [ 5.7634569 , 10.55251032]]])

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [183]:
import math

arr = np.random.random(10)
print(arr)
new_arr = np.sqrt(arr)
new_arr = np.where(new_arr < 0.5, 0, new_arr)
new_arr

[0.58703363 0.59203407 0.14447382 0.99500963 0.08647931 0.06679527
 0.43330657 0.91182819 0.23980836 0.18394554]


array([0.7661812 , 0.7694375 , 0.        , 0.99750169, 0.        ,
       0.        , 0.65826026, 0.95489695, 0.        , 0.        ])

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [210]:
arr1 = np.random.randint(12, size=random.randrange(0, 12))
arr2 = np.random.randint(12, size=random.randrange(0, 12))
print(arr1)
print(arr2)
maxVal = [np.amax(arr1),np.amax(arr2)]
arrMax = np.array([maxVal])
arrMax

[4 7 2 3 4 4]
[9 3 1 1 5 0]


array([[7, 9]])

36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [212]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
a = np.unique(names)
np.sort(a)
a

array(['Bob', 'Joe', 'Will'], dtype='<U4')

37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [213]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
val = np.intersect1d(a, b)

a = filter(lambda x: x if x not in val else None, a)
np.asarray(list(a))

array([1, 2, 3, 4])

38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [216]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
newColumn = np.array([[10,10,10]])

sampleArray[:, 1] = newColumn
sampleArray


array([[34, 10, 73],
       [82, 10, 12],
       [53, 10, 66]])

39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [217]:
x = np.array([[1., 2., 3.], [4., 5., 6.]]) 
y = np.array([[6., 23.], [-1, 7], [8, 9]])

np.dot(x, y)

array([[ 28.,  64.],
       [ 67., 181.]])

40. Generate a matrix of 20 random values and find its cumulative sum

In [265]:
mat1 = np.random.rand(4,5)
np.cumsum(mat1)

array([0.40504252, 0.49870543, 0.70120436, 1.49409692, 1.85091017,
       2.63323475, 2.74684107, 3.12954641, 3.56980627, 4.31157823,
       4.88501909, 5.27009072, 5.46278082, 5.49824637, 5.77589946,
       5.89680156, 6.78116411, 7.60258479, 8.51858047, 9.08322279])