# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [1]:
import numpy as np

arr1 = np.arange(10)
arr2 = arr1.reshape(2,5)
arr2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [10]:
arr1 = np.arange(10, dtype=int).reshape(2,5)
arr2 = np.ones(10, dtype=int).reshape(2,5)
np.vstack((arr1, arr2))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [11]:
np.hstack((arr1, arr2))

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [12]:
arr1.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [13]:
arr3d = np.asarray([[[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]]])
arr3d.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [14]:
arr1 = np.arange(15)
arr1.reshape(5,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [15]:
arr5x5 = np.arange(25).reshape(5, 5)
print("Array: ", arr5x5)
print("squaredArray: ", np.square(arr5x5))

Array:  [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
squaredArray:  [[  0   1   4   9  16]
 [ 25  36  49  64  81]
 [100 121 144 169 196]
 [225 256 289 324 361]
 [400 441 484 529 576]]


## Question:8

### Create 5x6 an array and find the mean?

In [17]:
arr5x6 = np.arange(30).reshape(5, 6)
print("array5x6: ", arr5x6)
print("Mean: ", np.mean(arr5x6))

array5x6:  [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
Mean:  14.5


## Question:9

### Find the standard deviation of the previous array in Q8?

In [18]:
print("Standard Deviation :", np.std(arr5x6))

Standard Deviation : 8.65544144839919


## Question:10

### Find the median of the previous array in Q8?

In [20]:
print("Median :", np.median(arr5x6))

Median : 14.5


## Question:11

### Find the transpose of the previous array in Q8?

In [23]:
np.transpose(arr5x6)

array([[ 0,  6, 12, 18, 24],
       [ 1,  7, 13, 19, 25],
       [ 2,  8, 14, 20, 26],
       [ 3,  9, 15, 21, 27],
       [ 4, 10, 16, 22, 28],
       [ 5, 11, 17, 23, 29]])

## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [25]:
arr4x4 = np.arange(16).reshape(4, 4)
print(arr4x4)
print("sum of diagonal elements is :", np.trace(arr4x4))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
sum of diagonal elements is : 30


## Question:13

### Find the determinant of the previous array in Q12?

In [27]:
np.linalg.det(arr4x4)

-2.9582283945787796e-30

## Question:14

### Find the 5th and 95th percentile of an array?

In [42]:
arr = np.arange(100)

print("5th percentile of arr : ", 
       np.percentile(arr, 5))
print("95th percentile of arr : ",
       np.percentile(arr, 95))

5th percentile of arr :  4.95
95th percentile of arr :  94.05


## Question:15

### How to find if a given array has any null values?

In [38]:
arr = np.array([1, 2, 3, 4, None, 5, 6, 7])

if None in arr:
    print("Array contains null value")
else:
    print("Array has no null value")


Array contains null value
